# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Evaluate hazard function based on outcome and year
#' @param OUTCOME 1 for dropout, 2 for transfer, 3 for graduation
#' @param YEAR Possible values 1:NYB in case of dropout/transfer; 1:NYA in case of graduation
#' @param THETA_CR Portion of the parameter vector related to the competing risk model
#' @param COVARIATES First 2 values for ability and speed. Remaining values are external covariates
#' @param NYB number of years in the non-graduatable state. Needed for determining how many time-related intercepts.
#' @param NYA number of years in the graduatable state. Needed for determining how many time-related intercepts.
#' @returns It returns the hazard probability of the specific outcome and year.
#' @export
hazard <- function(OUTCOME, YEAR, THETA_CR, COVARIATES, NYB, NYA) {
    .Call(`_studCRIRT_hazard`, OUTCOME, YEAR, THETA_CR, COVARIATES, NYB, NYA)
}

#' Extract parameters related to the competing risk model
extract_params_cr <- function(THETA_CR, DIM_EXT, NYB, NYA, OPTION) {
    .Call(`_studCRIRT_extract_params_cr`, THETA_CR, DIM_EXT, NYB, NYA, OPTION)
}

#' Extract parameters related to the IRT model
extract_params_irt <- function(THETA_IRT, N_GRADES, N_EXAMS, OPTION, EXAM) {
    .Call(`_studCRIRT_extract_params_irt`, THETA_IRT, N_GRADES, N_EXAMS, OPTION, EXAM)
}

