# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Evaluate hazard function based on outcome and year
#'
#' @param OUTCOME 1 for dropout, 2 for transfer, 3 for graduation
#' @param YEAR Possible values 1:NYB in case of dropout/transfer; 1:NYA in case of graduation
#' @param THETA_CR Portion of the parameter vector related to the competing risk model
#' @param COVARIATES The first 2 values refers to ability and speed respectively. Remaining values are external covariates
#' @param NYB number of years in the non-graduatable state. Needed for determining how many time-related intercepts.
#' @param NYA number of years in the graduatable state. Needed for determining how many time-related intercepts.
#' @param LOGFLAG Set TRUE to return log value.
#' @returns It returns the hazard probability of the specific outcome and year.
#'
#' @export
hazard <- function(OUTCOME, YEAR, THETA_CR, COVARIATES, NYB, NYA, LOGFLAG = FALSE) {
    .Call(`_studCRIRT_hazard`, OUTCOME, YEAR, THETA_CR, COVARIATES, NYB, NYA, LOGFLAG)
}

#' Evaluate survival function given a the range of years of interest
#'
#' @param YEAR_FIRST First year to evaluate.
#' @param YEAR_LAST Last year to evaluate.
#' @param THETA_CR Portion of the parameter vector related to the competing risk model
#' @param COVARIATES The first 2 values refers to ability and speed respectively. Remaining values are external predictors.
#' @param NYB Total number of years in the non-graduatable regime. Needed for determining how many time-related intercepts.
#' @param NYA Total number of years in the graduatable regime. Needed for determining how many time-related intercepts.
#' @param YEAR_LAST_EXAM Year at which the all exams are completed for the first time
#' @param LOGFLAG Set TRUE to return log value.
#'
#' @returns It returns the probability of survival from `YEAR FIRST` to `YEAR_LAST` included.
#'
#' @export
survival <- function(YEAR_FIRST, YEAR_LAST, THETA_CR, COVARIATES, NYB, NYA, YEAR_LAST_EXAM = 100L, LOGFLAG = FALSE) {
    .Call(`_studCRIRT_survival`, YEAR_FIRST, YEAR_LAST, THETA_CR, COVARIATES, NYB, NYA, YEAR_LAST_EXAM, LOGFLAG)
}

#' Evaluate Outcome Likelihood
#'
#' @param OUTCOME  `1` for dropout, `2` for transfer, `3` for graduation. `0` if no outcome is observed.
#' @param YEAR_FIRST First year to evaluate.
#' @param YEAR_LAST Last year to evaluate.
#' @param THETA_CR Portion of the parameter vector related to the competing risk model
#' @param COVARIATES The first 2 values refers to ability and speed respectively. Remaining values are external predictors.
#' @param NYB Total number of years in the non-graduatable regime. Needed for determining how many time-related intercepts.
#' @param NYA Total number of years in the graduatable regime. Needed for determining how many time-related intercepts.
#' @param YEAR_LAST_EXAM Year at which the all exams are completed for the first time.
#' @param LOGFLAG Set TRUE to return log value.
#'
#' @export
outcomeLik <- function(OUTCOME, YEAR_FIRST, YEAR_LAST, THETA_CR, COVARIATES, NYB, NYA, YEAR_LAST_EXAM = 100L, LOGFLAG = FALSE) {
    .Call(`_studCRIRT_outcomeLik`, OUTCOME, YEAR_FIRST, YEAR_LAST, THETA_CR, COVARIATES, NYB, NYA, YEAR_LAST_EXAM, LOGFLAG)
}

#' Intercepts reparameterisation
#'
#' @param X Intercepts or unconstrained parameter values for grades low-to-high.
#' @param CON2UN TRUE if going from the constrained space to the unconstrained one.
#'
#' @returns It allows to go back and forth from constrained intercepts
#' to unconstrained parameters.
#'
#' @export
cppReparInt <- function(X, CON2UN = TRUE) {
    .Call(`_studCRIRT_cppReparInt`, X, CON2UN)
}

#' Extract parameters indexes related to the competing risk model
#' @param THETA_CR Parameter vector related to the competing risk model
#' @param DIM_EXT Number of external covariates in the competing risk model.
#' @param NYB Number of years in the non-graduatable state. Needed for
#' determining how many time-related intercepts in the competing risk model.
#' @param NYA Number of years in the graduatable state.
#'  Needed for determining how many time-related intercepts in the competing risk model.
#' @param OPTION It selects the parameters of interest.
#' `1` for beta_d, `2` for beta_t, `3` for beta_g, `4` for beta0_d,
#' `5` for beta0_t, `6` for beta0_g.
#'
#' @returns It return a vector with two values representing the starting
#' index and the length of the segment of THETA_CR corresponding to
#' the parameter of interest
extract_params_idx_cr <- function(THETA_CR, DIM_EXT, NYB, NYA, OPTION) {
    .Call(`_studCRIRT_extract_params_idx_cr`, THETA_CR, DIM_EXT, NYB, NYA, OPTION)
}

#' Extract parameters related to the IRT model
#' @param THETA_IRT parameter vector related to irt model
#' @param N_GRADES number of grades modelled.
#' @param N_EXAMS number of exams.
#' @param OPTION Select parameters of interest. `1` for exam-grades slopes,
#' `2` for exam-grade intercepts, `3` for time-mean parameter,
#' `4` for time-var parameter.
#' @param EXAM exam of interest. Possible values in `1:N_EXAMS`.
#'
#' @returns It return a vector with two values representing the starting
#' index and the length of the segment of THETA_IRT corresponding to
#' the parameter of interest.
#'
#' @export
extract_params_idx_irt <- function(THETA_IRT, N_GRADES, N_EXAMS, OPTION, EXAM) {
    .Call(`_studCRIRT_extract_params_idx_irt`, THETA_IRT, N_GRADES, N_EXAMS, OPTION, EXAM)
}

#' Extract parameters related to the competing risk model
#' @param THETA_CR Parameter vector related to the competing risk model
#' @param DIM_EXT Number of external covariates in the competing risk model.
#' @param NYB Number of years in the non-graduatable state. Needed for
#' determining how many time-related intercepts in the competing risk model.
#' @param NYA Number of years in the graduatable state.
#'  Needed for determining how many time-related intercepts in the competing risk model.
#' @param OPTION It selects the parameters of interest.
#' `1` for beta_d, `2` for beta_t, `3` for beta_g, `4` for beta0_d,
#' `5` for beta0_t, `6` for beta0_g.
#'
extract_params_cr <- function(THETA_CR, DIM_EXT, NYB, NYA, OPTION) {
    .Call(`_studCRIRT_extract_params_cr`, THETA_CR, DIM_EXT, NYB, NYA, OPTION)
}

#' Extract parameters related to the IRT model
#' @param THETA_IRT parameter vector related to irt model
#' @param N_GRADES number of grades modelled.
#' @param N_EXAMS number of exams.
#' @param OPTION Select parameters of interest. `1` for exam-grades slopes,
#' `2` for exam-grade intercepts, `3` for time-mean parameter,
#' `4` for time-var parameter.
#' @param EXAM exam of interest. Posible values in `1:N_EXAMS`.
#' @export
extract_params_irt <- function(THETA_IRT, N_GRADES, N_EXAMS, OPTION, EXAM) {
    .Call(`_studCRIRT_extract_params_irt`, THETA_IRT, N_GRADES, N_EXAMS, OPTION, EXAM)
}

#' Evaluate the probability of grades greater or equal than the reference one
#'
#' @param GRADE Grade used as reference
#' @param EXAM Exam of interest
#' @param THETA_IRT Portion of the parameter vector related to the IRT model
#' @param N_GRADES Number of grades modelled.
#' @param N_EXAMS Number of exams.
#' @param ABILITY Ability value.
#' @param LOGFLAG Set TRUE to return log value.
#'
#' @returns It returns the probability of obtaining grades higher than `GRADE` on exam `EXAM`.
#'
#' @export
pGreaterGrades <- function(GRADE, EXAM, THETA_IRT, N_GRADES, N_EXAMS, ABILITY, LOGFLAG = FALSE) {
    .Call(`_studCRIRT_pGreaterGrades`, GRADE, EXAM, THETA_IRT, N_GRADES, N_EXAMS, ABILITY, LOGFLAG)
}

#' Evaluate the probability of getting a specific grade
#'
#' @param GRADE Grade used as reference
#' @param EXAM Exam of interest
#' @param THETA_IRT Portion of the parameter vector related to the IRT model
#' @param N_GRADES Number of grades modelled.
#' @param N_EXAMS Number of exams.
#' @param ABILITY Ability value.
#' @param LOGFLAG Set TRUE to return log value.
#'
#' @returns It returns the probability of obtaining the grade `GRADE` on exam `EXAM`.
#' @export
pGrade <- function(GRADE, EXAM, THETA_IRT, N_GRADES, N_EXAMS, ABILITY, LOGFLAG = FALSE) {
    .Call(`_studCRIRT_pGrade`, GRADE, EXAM, THETA_IRT, N_GRADES, N_EXAMS, ABILITY, LOGFLAG)
}

#' Evaluate the c.d.f or p.d.f of the last attempt to an exam
#'
#' @param EXAM Exam of interest.
#' @param DAY Day of interest.
#' @param THETA_IRT Portion of the parameter vector related to the IRT model
#' @param N_GRADES Number of grades modelled.
#' @param N_EXAMS Number of exams.
#' @param SPEED speed value.
#' @param CDFFLAG `TRUE` for c.d.f. of time. `FALSE` for p.d.f.
#' @param LOGFLAG Set TRUE to return log value.
#'
#' @export
pTimeExam <- function(EXAM, DAY, THETA_IRT, N_GRADES, N_EXAMS, SPEED, CDFFLAG, LOGFLAG = FALSE) {
    .Call(`_studCRIRT_pTimeExam`, EXAM, DAY, THETA_IRT, N_GRADES, N_EXAMS, SPEED, CDFFLAG, LOGFLAG)
}

#' Evaluate exam specific likelihood
#'
#' @param EXAM Exam of interest.
#' @param GRADE Grade of interest.
#' @param DAY Day of interest.
#' @param OBSFLAG TRUE for observed, FALSE for not-observed.
#' @param THETA_IRT Portion of the parameter vector related to the IRT model
#' @param N_GRADES Number of grades modelled.
#' @param N_EXAMS Number of exams.
#' @param ABILITY ability value.
#' @param SPEED speed value.
#' @param LOGFLAG Set TRUE to return log value.
#'
#' @returns It returns the probability of observing or not a specific
#' grade on a given exam before a given day conditioned on ability and speed.
#'
#' @export
examLik <- function(EXAM, GRADE, DAY, OBSFLAG, THETA_IRT, N_GRADES, N_EXAMS, ABILITY, SPEED, LOGFLAG = FALSE) {
    .Call(`_studCRIRT_examLik`, EXAM, GRADE, DAY, OBSFLAG, THETA_IRT, N_GRADES, N_EXAMS, ABILITY, SPEED, LOGFLAG)
}

#' Joint density of speed and ability
#'
#' @param ABILITY ability value.
#' @param SPEED speed value.
#' @param REPRHO atanh transformation of the latent correlation.
#' @param REPSIGMA log standard deviation of speed.
#' @param LOGFLAG `TRUE` for log density.
#'
#' @export
latent_distr <- function(ABILITY, SPEED, REPRHO, REPSIGMA, LOGFLAG = FALSE) {
    .Call(`_studCRIRT_latent_distr`, ABILITY, SPEED, REPRHO, REPSIGMA, LOGFLAG)
}

#' Evaluate the integrand function
#'
#' @param THETA Suitable parameter vector as provided by \link{paramsList2vec}().
#' @param EXTCOVARIATES External covariates.
#' @param EXAMS_GRADES Vector of grades.
#' @param EXAMS_DAYS Vector of times.
#' @param EXAMS_OBSFLAG Vector of booleans.
#' `TRUE` elements represent observed exams.
#' `FALSE` elements the unobserved ones.
#' @param OUTCOME  `1` for dropout, `2` for transfer, `3` for graduation. `0` if no outcome is observed.
#' @param YEAR Year of evaluation.
#' @param N_GRADES Number of grades modelled.
#' @param N_EXAMS Number of exams modelled
#' @param NYB Number of years in the non-graduatable state. Needed for determining how many time-related intercepts.
#' @param NYA Number of years in the graduatable state. Needed for determining how many time-related intercepts.
#' @param ABILITY Ability value.
#' @param SPEED Speed value.
#' @param YEAR_LAST_EXAM Year at which the all exams are completed for the first time.
#' @param LOGFLAG Set TRUE to return log value.
#'
#' @returns It returns the value of the integrand function,
#' given the parameters and the data of a single observation.
#'
#' @export
integrand <- function(THETA, EXTCOVARIATES, EXAMS_GRADES, EXAMS_DAYS, EXAMS_OBSFLAG, OUTCOME, YEAR, N_GRADES, N_EXAMS, NYB, NYA, ABILITY, SPEED, YEAR_LAST_EXAM = 100L, LOGFLAG = FALSE) {
    .Call(`_studCRIRT_integrand`, THETA, EXTCOVARIATES, EXAMS_GRADES, EXAMS_DAYS, EXAMS_OBSFLAG, OUTCOME, YEAR, N_GRADES, N_EXAMS, NYB, NYA, ABILITY, SPEED, YEAR_LAST_EXAM, LOGFLAG)
}

